version: "3"
services:
  web:
    build: .
    volumes:
      - .:/coffee:delegated
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  chrome:
    image: selenium/standalone-chrome-debug:latest
    shm_size: 128m
    ports:
      - "4444:4444"
      - "5900:5900"
volumes:
  mysql-data:
    driver: local
