version: "3"
services:
  web:
    build: ./rails
    volumes:
      - ./rails:/coffee-oma:delegated
    ports:
      - "3000:3000"
      - "3035:3035"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - chrome
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    command: --default-authentication-plugin=mysql_native_password
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - "4444:4444"
volumes:
  mysql-data:
    driver: local
