version: "3"
services:
  web:
    build: ./rails
    volumes:
      - ./rails:/coffee-oma:delegated
    ports:
      - "3000:3000"
      - "3036:3036"
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      REDIS_URL: redis://redis
    depends_on:
      - db
      - chrome
      - redis
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:delegated
    command: --default-authentication-plugin=mysql_native_password
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - "4444:4444"
  redis:
    image: redis:6.2.13-alpine3.18
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
volumes:
  mysql-data:
    driver: local
  redis-data:
