version: 2.1
jobs:
  build:
    docker:
      - image: tomoron/portfolio-coffee:latest
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
          MYSQL_USER: root
          MYSQL_DB: circleci_test
    working_directory: ~/coffee
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-bundle-v2-{{ checksum "Gemfile.lock"}}
            - rails-bundle-v2-
      - run:
          name: bundleをインストール
          command: bundle install
      - save_cache:
          key: rails-bundle-v2-{{ checkout "Gemfile.lock"}}
          paths:
            - vendor/bundle
