version: 2.1
jods:
  build:
    docker:
      - image: tomoron/portfolio-coffee
        auth:
          username: tomoron
          password: tomo32177
        enviroment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        enviroment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_DB: circleci_test
    working_directory: ~/coffee
    steps:
      - checkout
      - run:
        name: bundleをインストール
        command: bundle install
