version: 2.1
jobs:
  build:
    docker:
      - image: tomoron/portfolio-coffee:latest
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
          MYSQL_USER: root
          MYSQL_DB: circleci_test
    working_directory: ~/coffee
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
      - run:
          name: bundleをインストール
          command: bundle check || bundle install --jobs=4
      - run:
          name: yarnを追加
          command: yarn install
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
          paths:
            - vendor/bundle
            - ~/.node_modules
      - run:
          name: webpackを追加
          command: bundle exec bin/webpack
