version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@1.4.0
jobs:
  test:
    docker:
      - image: tomoron/portfolio-coffee:latest
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          ENV_FILE: $ENV_FILE
      - image: mysql:8.0
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_HOST: "127.0.0.1"
          MYSQL_DATABE: db
        command: --default-authentication-plugin=mysql_native_password
      - image: selenium/standalone-chrome-debug:latest
        name: chrome
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/coffee/rails
    steps:
      - checkout:
          path: ~/coffee
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - rails-gem-v2-{{ checksum "Gemfile.lock"}}
      - run:
          name: bundleをインストール
          command: bundle check || bundle install --jobs=4
      - save_cache:
          key: rails-gem-v2-{{ checksum "Gemfile.lock"}}
          paths:
            - /usr/local/bundle
      - restore_cache:
          keys:
            - rails-yarn-v1-{{ checksum "yarn.lock"}}
      - run:
          name: yarnを追加
          command: yarn install
      - save_cache:
          key: rails-yarn-v1-{{ checksum "yarn.lock"}}
          paths:
            - ~/coffee/rails/node_modules
      - run:
          name: webpackを追加
          command: bundle exec bin/webpack
      - run:
          name: Decode ENV file
          command: echo $ENV_FILE | base64 -d > .env
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: データベースを作成
          command: bundle exec rails db:create || bundle exec rails db:migrate
      - run:
          name: rspec test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: ./coverage
      - codecov/upload:
          file: ./coverage/codecov-result.json

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: deploy
          requires:
            - test
          name: rails-build-and-push-image
          account-url: AWS_ECR_ACCOUNT_URL
          path: "./rails"
          repo: "portfolio-rails"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          extra-build-args: "--build-arg ENV_FILE=${ENV_FILE}"
          dockerfile: Dockerfile.production
      - aws-ecs/deploy-service-update:
          filters:
            branches:
              only: deploy
          name: rails-deploy-service-update
          requires:
            - rails-build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: "portfolio-service"
          cluster-name: "portfolio-cluster"
          container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"
