version: 2.1
jobs:
  build:
    docker:
      - image: tomoron/portfolio-coffee:latest
        auth:
          username: tomoron
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABE: db
        command: --default-authentication-plugin=mysql_native_password
    working_directory: ~/coffee
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
      - run:
          name: bundleをインストール
          command: bundle check || bundle install --jobs=4
      - run:
          name: yarnを追加
          command: yarn install
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
          paths:
            - vendor/bundle
            - node_modules
      - run:
          name: webpackを追加
          command: bundle exec bin/webpack
      - run:
          name: データベースを作成
          command: bundle exec rails db:create || bundle exec rails db:migrate
      - run:
          name: rubocop
          command: bundle exec rubucop
      - run:
          name: rspec test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
