development:
  adapter: redis
  url: <% ENV['REDIS_URL'] %>
  port: 6379

test:
  adapter: test

production:
  adapter: redis
  port: 6379
  url: <% ENV['REDIS_AWS_URL']%>
  channel_prefix: coffee_production
